name: test-substrate-client

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: run docker image
      run: docker run -d -p 9944:9944 dylanverstraete/tfchain:2.1.0-b6 --dev --ws-external
      run: sleep 3

    - name: run test
      run: go test ./...
